# Dependencies # deprecated in Jekyll 3.0
# markdown:            redcarpet
# highlighter:         pygments

# Permalinks # deprecated in Jekyll 3.0
#
# Use of `relative_permalinks` ensures post links from the index work properly.
# permalink:           pretty
# relative_permalinks: false

# Setup
title: "Analyst 18"
tagline: "&nbsp; Software Engineering and other random() subjects"
description: "Articles on web-centric development that may or may not be related to Intelligence Analysis software."
url: https://dezoito.github.io
baseurl: /
paginate: 7

# About/contact
author:
  name:
  url: https://dezoito.github.io
  email:

# Custom vars
version: 1.0.0
