# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               'Dezoito &nbsp;'
tagline:             'Coding, Software Engineering, IBMs I-2, and other random() subjects'
description:         'Articles on web-centric development using Python, Django, Flask and ColdFusion, the I-2 suit, and custom Intelligence Analysis software.'
url:                 http://dezoito.github.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:
  url:               https://dezoito.github.io
  email:

# Custom vars
version:             1.0.0
