# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
# permalink:           pretty
# relative_permalinks: false # deprecated in Jekyll 3.0

# Setup
title:               'Analyst 18'
tagline:             '&nbsp; Software Engineering, IBM i2, code, and other random() subjects'
description:         'Articles on web-centric development using Python, Django, Flask and ColdFusion, the i2 suite, and custom Intelligence Analysis software.'
url:                 https://dezoito.github.io
baseurl:             /
paginate:            7

# About/contact
author:
  name:
  url:               https://dezoito.github.io
  email:

# Custom vars
version:             1.0.0
